Adds modal window
Katended/mobilefirstproject2 pull request #14
Opened 2023-04-20 12:59 UTC by Katended

The following have been addressed in this pull request:

- Add a modal window for mobile and desktop screen sizes.
- Add close icon.

2023-04-20 14:32 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)


# Hi @Katended 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- ## Please make sure you submit the appropriate PR for the milestone as I've noticed you submitted the [Mobile menu PR](https://github.com/Katended/mobilefirstproject2/pull/12) for the Popup milestone and it's causing confusion for us code reviewers when making the reviews.
- You just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 14:32 UTC, AbelG101 commented on modal.css
> +  }
- [ ] Good job adding the popup but it seems like some of the text is getting clipped as shown below, so please make sure to add a scroll feature for a better user experience. ✔
- Your design:
![5oI8FKYSjv](https://user-images.githubusercontent.com/104968236/233389655-56b51a4b-b3b3-4205-9062-1ad99e4ea80b.png)
- Figma design:
  ![image](https://user-images.githubusercontent.com/104968236/233390040-a70e63f2-6549-447c-a4d4-1cb36f4a3968.png)

- [ ] I've also noticed the spacing in the elements is bit disproportionate and not as shown in the Figma design so please make sure you fix that as well I've tried to highlight some of the visible ones below:
  ![Inked5oI8FKYSjv](https://user-images.githubusercontent.com/104968236/233391768-e739ea11-021a-4d40-984f-16f492c9b3a8.jpg)

2023-04-20 14:32 UTC, AbelG101 commented on modal.css
> +}
- [ ] The mobile popup could also use some adjustment as I've noticed the current height you've specified is filling up almost the entire screen so please make sure the height is similar as specified in the Figma design🎨:
- Your design:
  ![image](https://user-images.githubusercontent.com/104968236/233393609-a31beae6-7109-465d-be1f-186f48ff1cf7.png)
- Figma design:
  ![image](https://user-images.githubusercontent.com/104968236/233393744-b480b2e6-dcc7-4765-9e35-96c70efe40f2.png)
- As you can see from the above Figma design the height doesn't take up the entire screen.

2023-04-20 14:32 UTC, AbelG101 commented on modal.css
> +}
- [ ] I like that you're adding your own taste to the design here but you'll have to make sure you follow the given design at least at this stage as one of the objectives of this module is to give you the skill to implement any given design to near perfection 🎯
- Here's the Figma design for the hover state of the button:
  ![firefox_7KIb3eS8J1](https://user-images.githubusercontent.com/104968236/233395759-87b34909-50e7-4345-8ca7-a273e978acd0.png)

2023-04-21 08:03 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @Katended  👋, 

Great work on making the changes requested previously 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

 ## Required Changes ♻️
- _Check the comments under the review._
**- Please make sure you've addressed the previous changes that were requested before submitting for another review this will reduce your chances of getting requested for changes again. For now, you just have to make a few changes and you're on your way 🚀.**

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 16:15 UTC, frank1738 approved these changes
Hi  @Katended , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 17:52 UTC, merged