Add a contact Form
Katended/mobilefirstproject2 pull request #3
Opened 2023-04-04 10:39 UTC by Katended

The following have been added:

- Input validation for email, name and message
- Formpree action url

2023-04-04 13:56 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Katended, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Form working fine. ✔️
 - No linter errors. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 13:56 UTC, leonardodiasb commented on Index.html
> +</section>
- [ ] Your form is working fine and has a similar UI from the Figma template. But at the bottom, the form section seems to end after the `textarea` and the button seems to stay out of it, in an area with a grey background color. Kindly, make the contact section end at the bottom of the screen, and make sure that the buttom seems to stay inside the contact section which has a purple background color.
 - Your design:
 - 
<img width="480" alt="image" src="https://user-images.githubusercontent.com/61919617/229815321-878a465c-1f98-4659-ad00-c8b1ccc84e1c.png">

- Figma template:
- 
<img width="280" alt="image" src="https://user-images.githubusercontent.com/61919617/229815520-de1d4327-5a99-45f9-baa2-0782b9eaef6a.png">

2023-04-04 14:48 UTC, Ibizugbe approved these changes
Hi @Katended 👋👋, 

![INVALID](https://user-images.githubusercontent.com/64643995/229830003-4bb1856a-5e97-4e2e-82e2-bca513ca1f5b.gif)


While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have contributions from your learning partner🥲 don't forget, this is a pair programming activity and the contribution of your partner is also required😉 this was omitted by the first reviewer but it is a requirement😉 Kindly reach out to your learning partner and work with him👍

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-04 18:32 UTC, Ibizugbe commented
Hello @Katended   I think I stated the issue in the comment let me quote it here again ☺️

`You have submitted a project, that doesn't have contributions from your learning partner🥲 don't forget, this is a pair programming activity and the contribution of your partner is also required😉 this was omitted by the first reviewer but it is a requirement😉 Kindly reach out to your learning partner and work with him👍`

We require you to work with your pair programming partner for this milestone. From your commit message, it's seems you haven't done that. The previous reviewer should have pointed that but probably didn't take note of it.. but this is a compulsory requirement.👍

2023-04-04 18:34 UTC, Katended commented
> Hello @Katended I think I stated the issue in the comment let me quote it here again ☺️
> 
> `You have submitted a project, that doesn't have contributions from your learning partner🥲 don't forget, this is a pair programming activity and the contribution of your partner is also required😉 this was omitted by the first reviewer but it is a requirement😉 Kindly reach out to your learning partner and work with him👍`
> 
> We require you to work with your pair programming partner for this milestone. From your commit message, it's seems you haven't done that. The previous reviewer should have pointed that but probably didn't take note of it.. but this is a compulsory requirement.👍
> 
> Hope you're clear now?🤔

@Ibizugbe Ok sure thanks.

2023-04-04 18:41 UTC, Ibizugbe commented
Also @Katended , I noticed I made use of the `approve` feature to drop this comment, probably this may have caused a bit of confusion. but I sincerely apologise as that was a mistake on my part🥲 I should have dropped a normal comment or use the `comment` feature. But I am you understand now👍

Thanks for understanding and Happy coding👍

2023-04-04 19:54 UTC, NahnahAJ reviewed
## Project Status: INVALIDATED :red_circle: 
Hi @Katended , 

While you made a great effort in this project, I can't go ahead and review your code.
<img src="https://media2.giphy.com/media/TiUYdWptTqn8yOk1Dp/giphy.gif"/>

## Invalid Code Review Request

- This is because you have submitted a project, that is a [pair-programming activity](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#work-and-submission-mode) and as a result, needs to have commits from both you and your partner or partners just as the previous reviewer mentioned. :wink: 
- However, I noticed that you submitted the project again with only commits from you. This is the first collaboration milestone for you so please reach out to your partner and ensure that he or she adds commits to the project thereby collaborating in the project :100: 
- If for some reason you had to work on the project alone, then please add a screenshot of the email you received from student success stating that you can work alone so the next reviewer can proceed to review your project :wink: 
- Your commit history :thinking: 
![image](https://user-images.githubusercontent.com/102699958/229905039-1e453baf-d947-4d92-8236-cd45ac55846d.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-05 09:46 UTC, jerryowusu approved these changes
Hi @Team 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![chelsea-mason-approve](https://user-images.githubusercontent.com/65233860/230044893-efd48c0a-7ffb-4376-8598-84e4026348dd.gif)


## Highlights
Form working fine :heavy_check_mark: 
Used Github flow :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 14:39 UTC, merged